name: GitHub Social
template: github-social.html
width: 512
height: -1
default_params:
  left_text: Made by **me**!
  fa_icon: fas fa-laptop-house
  brand_text: My brand!
  background: https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/600px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg
